- topic: Accelerator Searching for Low-quality Dark Matter Solutions
  photo:
    name: # proj1.png
    scale: # 80%
  title:
    name: "AAA"
    link: http://XXX
    code: https://XXX
  site:
    link: https://XXX
    note: # with demo
  desc: " "
